apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: cm96qjs2s-python 
  janus-idp.io/tekton: cm96qjs2s-python
  backstage.io/kubernetes-id: cm96qjs2s-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: cm96qjs2s-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml