apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cm96qjs2s-python
  janus-idp.io/tekton: cm96qjs2s-python
  backstage.io/kubernetes-id: cm96qjs2s-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: cm96qjs2s-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
